"""Standard AI service errors."""


AI_VALIDATION_ERROR = "AI_VALIDATION_ERROR"
AI_PERMISSION_DENIED = "AI_PERMISSION_DENIED"
AI_NO_RELEVANT_DATA = "AI_NO_RELEVANT_DATA"
AI_EXTERNAL_SERVICE_FAILED = "AI_EXTERNAL_SERVICE_FAILED"
AI_LOW_CONFIDENCE = "AI_LOW_CONFIDENCE"
AI_PROCESSING_FAILED = "AI_PROCESSING_FAILED"
